### ISSUE TITLE
#include <hector_worldmodel_msgs/UserPercept.h>

### ISSUE THREAD

**Issue by LavrenovRoman** [tu-darmstadt-ros-pkg/hector_worldmodel_urdf_import#1]
Hello!
The file "hector_worldmodel_urdf_import.cpp" have a line #include <hector_worldmodel_msgs/UserPercept.h>. But there is no UserPercept.h in "hector_worldmodel_urdf_import" and "hector_worldmodel"
Thanks!

**Comment by skohlbr** [comment]
The line reads:
`#include <hector_worldmodel_msgs/UserPercept.h>`

The associated message type exists in the "fix_attributes" branch of hector_worldmodel: 
https://github.com/tu-darmstadt-ros-pkg/hector_worldmodel/blob/fix_attributes/hector_worldmodel_msgs/msg/UserPercept.msg

Note this is experimental code that won't be very useful to you unless you know exactly what you want to do with it.

**Comment by LavrenovRoman** [comment]
Okay:) thank you
